replicaCount: 1
image:
  repository: chartmuseum/chartmuseum
  tag: v0.2.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 80m
    memory: 64Mi

storage: "google" # only google and local are supported for the moment

# if storage==google, these must be defined, and a gke-credentials.json file be present
googleCloudStoragePrefix: ""
googleCloudStorageBucket: "fleet-chartmuseum"
