apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: {{ include "common.fullname" . }}
      labels:
        app: {{ template "common.name" . }}
        release: {{ .Release.Name | quote }}
    spec:
      volumes:
      - name: storage-volume
        emptyDir: {}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --port={{ .Values.service.internalPort }}
        - --debug
        - --storage=google
        - --storage-google-bucket={{ .Values.googleCloudStorageBucket }}
        - --storage-google-prefix={{ .Values.googleCloudStoragePrefix }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        # livenessProbe:
        #   httpGet:
        #     path: /index.yaml
        #     port: {{ .Values.service.internalPort }}
        # readinessProbe:
        #   httpGet:
        #     path: /index.yaml
        #     port: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- if eq $.Values.storage "google" }}
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/credentials/gke-credentials.json"
        volumeMounts:
        - name: credentials-volume
          mountPath: /etc/credentials
      volumes:
      - name: credentials-volume
        configMap:
          name: {{ $.Chart.Name }}-{{ $.Release.Name }}-credentials
{{- end }}
        # volumeMounts:
        # - mountPath: /storage
        #   name: storage-volume
